-- ==========================================
-- PHẦN DÀNH RIÊNG CHO QUẢN TRỊ VIÊN (ADMIN)
-- ==========================================

-- 1. CÁC VIEW DÀNH CHO ADMIN
-- View quản lý tài khoản (kèm tên vai trò)
CREATE OR REPLACE VIEW V_ADMIN_TAIKHOAN AS
SELECT tk.MATK, tk.EMAIL, tk.HOTEN, tk.SDT, tk.MAVAITRO, vt.TENVAITRO
FROM TAIKHOAN tk
JOIN VAITRO vt ON tk.MAVAITRO = vt.MAVAITRO
ORDER BY tk.MATK DESC;

-- View quản lý cửa hàng (kèm thông tin chủ cửa hàng)
CREATE OR REPLACE VIEW V_ADMIN_CUAHANG AS
SELECT ch.MACH, ch.TENCH, ch.DIACHI, ch.TRANGTHAI, ch.MATK, tk.EMAIL, tk.HOTEN AS TENCHUCUAHANG
FROM CUAHANG ch
JOIN TAIKHOAN tk ON ch.MATK = tk.MATK
ORDER BY ch.MACH DESC;

-- View quản lý loại sản phẩm (Danh mục)
CREATE OR REPLACE VIEW V_ADMIN_LOAISP AS
SELECT MALOAI, TENLOAI
FROM LOAISP
ORDER BY MALOAI DESC;

-- View quản lý toàn bộ sản phẩm trên hệ thống
CREATE OR REPLACE VIEW V_ADMIN_SANPHAM AS
SELECT sp.MASP, sp.TENSP, sp.DONGIA, sp.SOLUONGTON, sp.HINHANH, 
       ls.TENLOAI, ch.TENCH
FROM SANPHAM sp
JOIN LOAISP ls ON sp.MALOAI = ls.MALOAI
JOIN CUAHANG ch ON sp.MACH = ch.MACH
ORDER BY sp.MASP DESC;

-- View quản lý toàn bộ đơn hàng trên hệ thống
CREATE OR REPLACE VIEW V_ADMIN_HOADON AS
SELECT hd.MAHD, hd.NGAYLAP, hd.TONGTIEN, hd.TRANGTHAI, hd.DIACHIGIAO, 
       tk.HOTEN AS MANGUOIDAT, pt.TENPTTT
FROM HOADON hd
JOIN TAIKHOAN tk ON hd.MATK = tk.MATK
JOIN PTTT pt ON hd.MAPTTT = pt.MAPTTT
ORDER BY hd.NGAYLAP DESC;

-- Thống kê tổng số lượng (Dashboard Tóm tắt)
CREATE OR REPLACE VIEW V_ADMIN_THONGKE AS
SELECT 
    (SELECT COUNT(*) FROM TAIKHOAN) AS TONG_TAIKHOAN,
    (SELECT COUNT(*) FROM CUAHANG) AS TONG_CUAHANG,
    (SELECT COUNT(*) FROM SANPHAM) AS TONG_SANPHAM,
    (SELECT COUNT(*) FROM HOADON) AS TONG_HOADON,
    (SELECT NVL(SUM(TONGTIEN), 0) FROM HOADON WHERE TRANGTHAI = 'HOÀN THÀNH') AS DOANHTHU_HETHONG
FROM DUAL;


-- 2. CÁC PROCEDURE THỰC HIỆN CRUD CHO ADMIN

-- CRUD TAIKHOAN
CREATE OR REPLACE PROCEDURE SP_ADMIN_THEM_TAIKHOAN(
    p_email IN VARCHAR2,
    p_matkhau IN VARCHAR2,
    p_hoten IN NVARCHAR2,
    p_sdt IN VARCHAR2,
    p_mavaitro IN NUMBER
) IS
BEGIN
    INSERT INTO TAIKHOAN (EMAIL, MATKHAU, HOTEN, SDT, MAVAITRO) 
    VALUES (p_email, p_matkhau, p_hoten, p_sdt, p_mavaitro);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_ADMIN_SUA_TAIKHOAN(
    p_matk IN NUMBER,
    p_hoten IN NVARCHAR2,
    p_sdt IN VARCHAR2,
    p_mavaitro IN NUMBER
) IS
BEGIN
    UPDATE TAIKHOAN 
    SET HOTEN = p_hoten, SDT = p_sdt, MAVAITRO = p_mavaitro
    WHERE MATK = p_matk;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_ADMIN_XOA_TAIKHOAN(
    p_matk IN NUMBER
) IS
BEGIN
    -- Lưu ý: Lệnh xóa có thể bị lỗi vướng Khóa ngoại (Foreign Key Constraints)
    -- nếu tài khoản đó đã có hóa đơn hoặc có hàng hóa, cửa hàng.
    -- Xử lý cơ bản xóa theo yêu cầu cấu trúc hiện tại.
    DELETE FROM TAIKHOAN WHERE MATK = p_matk;
    COMMIT;
END;
/

-- CRUD LOAISP (Danh mục)
CREATE OR REPLACE PROCEDURE SP_ADMIN_THEM_LOAISP(
    p_tenloai IN NVARCHAR2
) IS
BEGIN
    INSERT INTO LOAISP (TENLOAI) VALUES (p_tenloai);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_ADMIN_SUA_LOAISP(
    p_maloai IN NUMBER,
    p_tenloai IN NVARCHAR2
) IS
BEGIN
    UPDATE LOAISP SET TENLOAI = p_tenloai WHERE MALOAI = p_maloai;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_ADMIN_XOA_LOAISP(
    p_maloai IN NUMBER
) IS
BEGIN
    DELETE FROM LOAISP WHERE MALOAI = p_maloai;
    COMMIT;
END;
/

-- Quản lý CUAHANG
CREATE OR REPLACE PROCEDURE SP_ADMIN_SUA_CUAHANG(
    p_mach IN NUMBER,
    p_trangthai IN NVARCHAR2
) IS
BEGIN
    UPDATE CUAHANG SET TRANGTHAI = p_trangthai WHERE MACH = p_mach;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_ADMIN_XOA_CUAHANG(
    p_mach IN NUMBER
) IS
BEGIN
    DELETE FROM CUAHANG WHERE MACH = p_mach;
    COMMIT;
END;
/
