-- View 1: Menu Danh mục
CREATE OR REPLACE VIEW V_MENU_DANHMUC AS
SELECT MALOAI, TENLOAI FROM LOAISP ORDER BY TENLOAI;

-- View 2: Hiển thị lưới Sản phẩm trên Web (Chỉ hiện SP còn hàng và shop đang HĐ)
CREATE OR REPLACE VIEW V_CHITIET_SANPHAM_WEB AS
SELECT sp.MASP, sp.TENSP, sp.MOTA, sp.DONGIA, sp.SOLUONGTON, sp.HINHANH, 
       l.TENLOAI, ch.TENCH, ch.MACH
FROM SANPHAM sp
JOIN LOAISP l ON sp.MALOAI = l.MALOAI
JOIN CUAHANG ch ON sp.MACH = ch.MACH
WHERE sp.SOLUONGTON > 0 AND ch.TRANGTHAI = 'HOẠT ĐỘNG';

-- View 3: Xem chi tiết Giỏ hàng
CREATE OR REPLACE VIEW V_CHITIET_GIOHANG AS
SELECT gh.MATK, ct.MAGH, ct.MASP, sp.TENSP, sp.HINHANH, sp.DONGIA, ct.SOLUONG, 
       (sp.DONGIA * ct.SOLUONG) AS THANHTIEN
FROM CTGH ct
JOIN GIOHANG gh ON ct.MAGH = gh.MAGH
JOIN SANPHAM sp ON ct.MASP = sp.MASP;

-- View 4: Lịch sử Đơn hàng của Khách
CREATE OR REPLACE VIEW V_LICHSU_DONHANG_KHACH AS
SELECT hd.MAHD, hd.MATK, hd.NGAYLAP, hd.TONGTIEN, hd.TRANGTHAI, hd.DIACHIGIAO, pt.TENPTTT
FROM HOADON hd
JOIN PTTT pt ON hd.MAPTTT = pt.MAPTTT
ORDER BY hd.NGAYLAP DESC;

-- View 5: Xem chi tiết của 1 Đơn hàng
CREATE OR REPLACE VIEW V_CHITIET_HOADON AS
SELECT ct.MAHD, sp.MASP, sp.TENSP, sp.HINHANH, ct.SOLUONG, ct.DONGIALUCMUA, 
       (ct.SOLUONG * ct.DONGIALUCMUA) AS THANHTIEN
FROM CTHD ct
JOIN SANPHAM sp ON ct.MASP = sp.MASP;

-- View 6: Quản lý Đơn hàng dành cho Chủ Cửa Hàng
CREATE OR REPLACE VIEW V_DONHANG_CUA_SHOP AS
SELECT hd.MAHD, hd.NGAYLAP, hd.TRANGTHAI, tk.HOTEN AS TENKHACHHANG, hd.DIACHIGIAO,
       sp.TENSP, ct.SOLUONG, ct.DONGIALUCMUA, (ct.SOLUONG * ct.DONGIALUCMUA) AS THANHTIEN,
       ch.MACH, ch.MATK AS MATK_CHUSHOP
FROM HOADON hd
JOIN TAIKHOAN tk ON hd.MATK = tk.MATK
JOIN CTHD ct ON hd.MAHD = ct.MAHD
JOIN SANPHAM sp ON ct.MASP = sp.MASP
JOIN CUAHANG ch ON sp.MACH = ch.MACH;

